### ISSUE TITLE
rc.d script

### ISSUE THREAD

**Issue by chocolait** [skunkwerks/freebsd-ports#2]
Hi Dave,
I appreciate your h2o port but I seem to stumble each time I try to run
```
sudo service h2o start
Starting h2o.

sudo service h2o status
h2o is not running.
```

I am sure the problem is simple, but I am a noob who can't debug rc.d script because I can run this just fine.
```
sudo h2o --conf /usr/local/etc/h2o/h2o.conf
```

my config:
```
listen: 80
user: www
access-log: /var/log/h2o/h2o.log
file.dirlisting: on
hosts:
    www.example.com:
        paths:
            "/":
                file.dir: "/home/www/example.com"
```

Thanks for your time.
